[build]
builder = "nixpacks"
buildCommand = "npm install --legacy-peer-deps && npx prisma generate && npm run build"

[deploy]
startCommand = "node dist/main"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
